apiVersion: v1
kind: Pod
metadata:
  name: curly
spec:
  containers:
    - name: curl-client
      image: curlimages/curl
      command: ["/bin/sh","-c"]
      args:
        - sleep 5; watch -n 10 "curl -H '$SUPERSECRETHEADER' sinatra-service"
      tty: true
      env:
        - name: SUPERSECRETHEADER
          value: "SUPERSECRETACCESSKEY: foob"
  nodeSelector:
    type: client
